[build]
  publish = "doc/build"
  # https://github.com/netlify/build-image/issues/221#issuecomment-504385202
  # https://github.com/netlify/build-image/issues/221#issuecomment-644662189
  command = """
pip install -q poetry==1.1.7 &&
poetry install &&
sphinx-build -W -b singlehtml doc doc/build
"""
