[build]
  publish = "build"
  # https://github.com/netlify/build-image/issues/221#issuecomment-504385202
  # https://github.com/netlify/build-image/issues/221#issuecomment-644662189
  command = """
pip3 install -q poetry==1.2.0a1 &&
poetry config settings.virtualenvs.in-project true &&
poetry install &&
./dev.py doc
"""
